//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_Form.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lab_Form.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459164_54c2w4kmje_m_1200x689_800x459_400x230 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459164-54c2w4kmje_m_1200x689_800x459_400" +
                        "x230", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459164_54c2w4kmje_m_1200x689_800x459_400x2301 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459164-54c2w4kmje_m_1200x689_800x459_400" +
                        "x2301", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459201_inllbzqckw_m_1200x561_800x374_400x187 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459201-inllbzqckw_m_1200x561_800x374_400" +
                        "x187", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459201_inllbzqckw_m_1200x561_800x374_400x1871 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459201-inllbzqckw_m_1200x561_800x374_400" +
                        "x1871", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459212_o7qfa51uau_m_1200x486_800x324_400x162 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459212-o7qfa51uau_m_1200x486_800x324_400" +
                        "x162", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459212_o7qfa51uau_m_1200x486_800x324_400x1621 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459212-o7qfa51uau_m_1200x486_800x324_400" +
                        "x1621", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459223_cptmjptwag_m_1200x607_800x404_400x202 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459223-cptmjptwag_m_1200x607_800x404_400" +
                        "x202", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459223_cptmjptwag_m_1200x607_800x404_400x2021 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459223-cptmjptwag_m_1200x607_800x404_400" +
                        "x2021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459233_nhz4x4sloj_m_1200x587_800x391_400x196 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459233-nhz4x4sloj_m_1200x587_800x391_400" +
                        "x196", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459233_nhz4x4sloj_m_1200x587_800x391_400x1961 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459233-nhz4x4sloj_m_1200x587_800x391_400" +
                        "x1961", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459242_ukciqcldnd_m_1200x582_800x388_400x194 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459242-ukciqcldnd_m_1200x582_800x388_400" +
                        "x194", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459242_ukciqcldnd_m_1200x582_800x388_400x1941 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459242-ukciqcldnd_m_1200x582_800x388_400" +
                        "x1941", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459257_dgnazd3jen_m_1200x490_800x327_400x163 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459257-dgnazd3jen_m_1200x490_800x327_400" +
                        "x163", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459257_dgnazd3jen_m_1200x490_800x327_400x1631 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459257-dgnazd3jen_m_1200x490_800x327_400" +
                        "x1631", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459280_t8fdrihe32_m_1200x723_800x482_400x241 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459280-t8fdrihe32_m_1200x723_800x482_400" +
                        "x241", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459280_t8fdrihe32_m_1200x723_800x482_400x2411 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459280-t8fdrihe32_m_1200x723_800x482_400" +
                        "x2411", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459302_fe01nmrmcs_m_1200x553_800x369_400x184 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459302-fe01nmrmcs_m_1200x553_800x369_400" +
                        "x184", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459302_fe01nmrmcs_m_1200x553_800x369_400x1841 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459302-fe01nmrmcs_m_1200x553_800x369_400" +
                        "x1841", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459314_irikwluke9_m_1200x500_800x333_400x167 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459314-irikwluke9_m_1200x500_800x333_400" +
                        "x167", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459314_irikwluke9_m_1200x500_800x333_400x1671 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459314-irikwluke9_m_1200x500_800x333_400" +
                        "x1671", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459330_oicyua9wt0_m_1200x598_800x399_400x199 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459330-oicyua9wt0_m_1200x598_800x399_400" +
                        "x199", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _21d28038_6d71_4f5d_af8c_c54ed483e2ba_1641459330_oicyua9wt0_m_1200x598_800x399_400x1991 {
            get {
                object obj = ResourceManager.GetObject("21d28038-6d71-4f5d-af8c-c54ed483e2ba-1641459330-oicyua9wt0_m_1200x598_800x399_400" +
                        "x1991", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
